# Generated by Django 2.1 on 2018-09-04 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'my_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BaiLamHocSinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dap_an', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bai_lam_hoc_sinh',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CauHoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateField(default=django.utils.timezone.now)),
                ('noi_dung', models.TextField()),
            ],
            options={
                'db_table': 'cau_hoi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChiTietDe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cau_hoi', models.ForeignKey(db_column='cau_hoi_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.CauHoi')),
            ],
            options={
                'db_table': 'chi_tiet_de',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChiTietLop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'chi_tiet_lop',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChiTietNhom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myuser_id', models.ForeignKey(db_column='myuser_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chi_tiet_nhom',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DapAn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('dap_an_dung', models.BooleanField()),
                ('cau_hoi_id', models.ForeignKey(db_column='cau_hoi_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.CauHoi')),
            ],
            options={
                'db_table': 'dap_an',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='De',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('ngay_tao', models.DateField(default=django.utils.timezone.now)),
                ('loai_de', models.IntegerField()),
            ],
            options={
                'db_table': 'de',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiemSo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dap_an', models.CharField(max_length=255)),
                ('ngay_lam', models.DateField(default=django.utils.timezone.now)),
                ('de_id', models.ForeignKey(db_column='de_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.De')),
                ('myuser_id', models.ForeignKey(db_column='myuser_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diem_so',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GiaoVienMon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'giao_vien_mon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lop',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('lop', models.IntegerField()),
                ('mo_ta', models.TextField()),
            ],
            options={
                'db_table': 'mon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nhom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhom', models.CharField(max_length=255)),
                ('myuser_id', models.ForeignKey(db_column='myuser_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nhom',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Truong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('mo_ta', models.TextField()),
            ],
            options={
                'db_table': 'truong',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='lop',
            name='truong_id',
            field=models.ForeignKey(db_column='truong_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.Truong'),
        ),
        migrations.AddField(
            model_name='giaovienmon',
            name='mon_id',
            field=models.ForeignKey(db_column='mon_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.Mon'),
        ),
        migrations.AddField(
            model_name='giaovienmon',
            name='myuser_id',
            field=models.ForeignKey(db_column='myuser_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='de',
            name='mon',
            field=models.ForeignKey(db_column='mon_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.Mon'),
        ),
        migrations.AddField(
            model_name='de',
            name='myuser_id',
            field=models.ForeignKey(db_column='myuser_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dapan',
            name='mon_id',
            field=models.ForeignKey(db_column='mon_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.Mon'),
        ),
        migrations.AddField(
            model_name='chitietnhom',
            name='nhom_id',
            field=models.ForeignKey(db_column='nhom_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.Nhom'),
        ),
        migrations.AddField(
            model_name='chitietlop',
            name='lop_id',
            field=models.ForeignKey(db_column='lop_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.Lop'),
        ),
        migrations.AddField(
            model_name='chitietlop',
            name='myuser_id',
            field=models.ForeignKey(db_column='myuser_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chitietde',
            name='de_id',
            field=models.ForeignKey(db_column='de_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.De'),
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='mon_id',
            field=models.ForeignKey(db_column='mon_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.Mon'),
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='myuser_id',
            field=models.ForeignKey(db_column='myuser_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bailamhocsinh',
            name='cau_hoi_id',
            field=models.ForeignKey(db_column='cau_hoi_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.CauHoi'),
        ),
        migrations.AddField(
            model_name='bailamhocsinh',
            name='de_id',
            field=models.ForeignKey(db_column='de_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.De'),
        ),
        migrations.AddField(
            model_name='bailamhocsinh',
            name='myuser_id',
            field=models.ForeignKey(db_column='myuser_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myuser',
            name='truong_id',
            field=models.ForeignKey(db_column='truong_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Truong'),
        ),
    ]
