# Generated by Django 2.1 on 2018-09-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='gioi_tinh',
            field=models.IntegerField(null=True),
        ),
    ]
