# Generated by Django 2.1.1 on 2018-09-11 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_myuser_gioi_tinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='diemso',
            name='mon',
            field=models.ForeignKey(db_column='mon_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.Mon'),
            preserve_default=False,
        ),
    ]
