# Generated by Django 2.1.1 on 2018-09-11 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_diemso_mon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diemso',
            name='dap_an',
        ),
    ]
