# Generated by Django 2.1 on 2018-09-12 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_diemso_dap_an'),
    ]

    operations = [
        migrations.AddField(
            model_name='diemso',
            name='loai_diem',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='de',
            name='loai_de',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diemso',
            name='de_id',
            field=models.ForeignKey(db_column='de_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.De'),
        ),
        migrations.AlterField(
            model_name='diemso',
            name='myuser_id',
            field=models.ForeignKey(db_column='myuser_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
