# Generated by Django 2.1 on 2018-09-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20180912_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='diemso',
            name='diem',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
