# Generated by Django 2.1 on 2018-09-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20180913_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chitietde',
            old_name='cau_hoi',
            new_name='cau_hoi_id',
        ),
        migrations.RenameField(
            model_name='de',
            old_name='mon',
            new_name='mon_id',
        ),
        migrations.RenameField(
            model_name='diemso',
            old_name='mon',
            new_name='mon_id',
        ),
    ]
