# Generated by Django 2.1 on 2018-09-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_cauhoi_dinh_kem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhoi',
            name='dinh_kem',
            field=models.FileField(blank=True, null=True, upload_to='question_upload'),
        ),
    ]
