# Generated by Django 2.1.1 on 2018-10-02 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_auto_20180924_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhom',
            name='lop_id',
            field=models.ForeignKey(db_column='lopid', null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Lop'),
        ),
    ]
