# Generated by Django 2.1 on 2018-10-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_nhom_lop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='de',
            name='cau_truc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
