# Generated by Django 2.1 on 2018-10-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_de_cau_truc'),
    ]

    operations = [
        migrations.AddField(
            model_name='de',
            name='chi_tiet_so_luong',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='de',
            name='so_luong',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='de',
            name='cau_truc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
