# Generated by Django 2.1 on 2018-10-04 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_auto_20181004_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='lop',
            name='khoa_id',
            field=models.ForeignKey(db_column='khoa_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Khoa'),
        ),
        migrations.AddField(
            model_name='lop',
            name='nien_khoa_id',
            field=models.ForeignKey(db_column='nien_khoa_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.NienKhoa'),
        ),
    ]
