# Generated by Django 2.1 on 2018-10-05 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_auto_20181004_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauHoiDa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateField(default=django.utils.timezone.now)),
                ('noi_dung', models.TextField()),
                ('do_kho', models.IntegerField()),
                ('chu_de', models.CharField(max_length=255)),
                ('dang_cau_hoi', models.CharField(max_length=255)),
                ('dinh_kem', models.FileField(blank=True, null=True, upload_to='question_upload')),
                ('so_cau_hoi', models.IntegerField()),
                ('mon_id', models.ForeignKey(db_column='mon_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.Mon')),
                ('myuser_id', models.ForeignKey(db_column='myuser_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cau_hoi_da',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChiTietCauHoiDa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cau_hoi_da_id', models.ForeignKey(db_column='cau_hoi_da_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.CauHoiDa')),
            ],
            options={
                'db_table': 'chi_tiet_cau_hoi_da',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='don',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dapan',
            name='dinh_kem',
            field=models.FileField(blank=True, null=True, upload_to='question_upload'),
        ),
        migrations.AddField(
            model_name='chitietcauhoida',
            name='cau_hoi_id',
            field=models.ForeignKey(db_column='cau_hoi_id', on_delete=django.db.models.deletion.CASCADE, to='teacher.CauHoi'),
        ),
    ]
