# Generated by Django 2.1 on 2018-10-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_cauhoida_dung_lam'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauhoi',
            name='so_dap_an_dung',
            field=models.IntegerField(default=1),
        ),
    ]
