# Generated by Django 2.1 on 2018-10-08 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0022_cauhoi_so_dap_an_dung'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietde',
            name='cau_hoi_da_id',
            field=models.ForeignKey(db_column='cau_hoi_da_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.CauHoiDa'),
        ),
        migrations.AlterField(
            model_name='chitietde',
            name='cau_hoi_id',
            field=models.ForeignKey(db_column='cau_hoi_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.CauHoi'),
        ),
    ]
