# Generated by Django 2.1 on 2018-10-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0023_auto_20181008_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diemso',
            old_name='diem',
            new_name='diem_auto',
        ),
        migrations.AddField(
            model_name='diemso',
            name='diem_cham_tay',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
