# Generated by Django 2.1 on 2018-10-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0024_auto_20181011_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diemso',
            name='diem_auto',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diemso',
            name='diem_cham_tay',
            field=models.FloatField(null=True),
        ),
    ]
