# Generated by Django 2.1 on 2018-10-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0026_auto_20181011_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='diemso',
            name='da_cham_diem',
            field=models.BooleanField(default=False),
        ),
    ]
