# Generated by Django 2.1 on 2018-10-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0027_diemso_da_cham_diem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diemso',
            name='da_cham_diem',
            field=models.BooleanField(default=True),
        ),
    ]
