# Generated by Django 2.1.2 on 2018-10-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0028_auto_20181015_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='noti_chat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='noti_noti',
            field=models.IntegerField(default=0),
        ),
    ]
